//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHUETRO_BAOOANH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIENBANSUCO
    {
        public string SoBB { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string LyDo { get; set; }
        public string HinhThucXuLy { get; set; }
        public string MaSC { get; set; }
        public string MaPT { get; set; }
        public string MaNV { get; set; }
        public string MaKH { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual PHONGTRO PHONGTRO { get; set; }
        public virtual SUCO SUCO { get; set; }
    }
}
