//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHUETRO_BAOOANH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAIPHONGTRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAIPHONGTRO()
        {
            this.PHONGTROes = new HashSet<PHONGTRO>();
        }
    
        public string MaLPT { get; set; }
        public string TenLPT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONGTRO> PHONGTROes { get; set; }
    }
}
