//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHUETRO_BAOOANH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.BIENBANSUCOes = new HashSet<BIENBANSUCO>();
            this.HOPDONGs = new HashSet<HOPDONG>();
            this.PHIEUTHUTIENs = new HashSet<PHIEUTHUTIEN>();
        }
    
        public string MaNV { get; set; }
        public string HoTenNV { get; set; }
        public Nullable<System.DateTime> NgaySinhNV { get; set; }
        public Nullable<bool> GioiTinhNV { get; set; }
        public string DiaChiNV { get; set; }
        public string SdtNV { get; set; }
        public string SoCMND { get; set; }
        public string AnhNV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIENBANSUCO> BIENBANSUCOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOPDONG> HOPDONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUTHUTIEN> PHIEUTHUTIENs { get; set; }
    }
}
